### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create starter HTML, CSS, JS files
- [x] Create an img element with a picture of the car as the src
- [x] Change size of the car if needed
- [x] Change the CSS to have the background as green
