### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create CSS rules for when the car faces north, west, south, east
- [x] Create event listener for when the user uses the keyboard to change direction and apply correct CSS rule
- [x] Remove any unnecessary CSS
- [x] Check for errors

**Comment by AsfandToor** [comment]
I'll do this.

**Comment by AsfandToor** [comment]
I can do this but why aren't you using canvas?
