### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add x and y coordinates to data model
- [x] Set the car image to absolute
- [x] Toggle car to start
