### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Create a interval ID for movement
- [x] Create a boolean for if the car is already started or not
- [x] Check if car is started on space keydown and if it is, clear the interval
